services:
  wg-easy:
    environment:
      - WG_HOST=43.128.45.32
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.32.x
      - WG_DEFAULT_DNS=192.168.31.45(wireguard DNS服务器)
      - WG_MTU=1420
      - WG_ALLOWED_IPS=192.168.31.0/24,192.168.32.0/24
      - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: "host"


